### ISSUE TITLE
csswring 3.0.0 bug

### ISSUE THREAD

**Issue by deployable** [adunkman/connect-assets#307]
Using a library called w2ui has a less style like so https://github.com/vitmalina/w2ui/blob/master/src/less/src/common.less#L84

```less
    input:not([type=button]), select, textarea {
        padding: 4px;
        border: @input-border;
        border-radius: 3px;
        color: @input-color;
        background-color: @input-background-color;
        line-height: normal;
        &:focus {
            outline-color: @input-focus-outline-color;    
        }
        &:disabled, &[readonly] {
            background-color: #f1f1f1;
            color: #777;
        }    
    }
```

Straight through less in development mode it comes out as:

```css
input:not([type=button]):disabled,
select:disabled,
textarea:disabled,
input:not([type=button])[readonly],
select[readonly],
textarea[readonly] {
  background-color: #f1f1f1;
  color: #777;
}
```

Through csswring, when the app is in production mode. 

```css
input:not([type=button]):disabled,select:disabled,textarea:disabled,input:not([type="button])[readonly"],select[readonly],textarea[readonly] {
    background-color: #f1f1f1;
    color: #777
}
```

This problem string in question

```css
input:not([type="button])[readonly"]
```

csswring 3.0.5 can parse this correctly. 
Updating my local connect-assets `package.json` to `"csswring": "~3.0.5"` fixed the issue.

Could the included csswring be updated to the latest patch release?
